name: snakeymakey

channels:
  - conda-forge

dependencies:
  - datrie # for snakemake
  - graphviz # for snakemake graph
  - hydromt # for weathergen
  - jupyter # to run examples
  - matplotlib # to run example
  - numba # for weathergen
  - numpy
  - pandas # for paramspace
  - pip
  - python>=3.8
  - pip:
    - snakemake==7.8.0
